"use client";
import { useState } from "react";
import type { CCtx } from "../CreatorApp";
import { CREATORS } from "@/data/creators";
import CreatorCardPreview from "../CreatorCardPreview";
import { fmtK, initials } from "@/lib/format";

export default function Community({ ctx }: { ctx: CCtx }) {
  const [metric, setMetric] = useState<"impressions" | "posts">("impressions");
  const board = [...CREATORS].sort((a, b) => b.medianViews * 6 - a.medianViews * 6).slice(0, 10).map((c, i) => ({ name: c.name, slug: c.slug, impressions: c.medianViews * (8 - Math.min(i, 5)), posts: 9 - Math.min(i, 6) }));
  const max = Math.max(...board.map((b) => (metric === "impressions" ? b.impressions : b.posts)));
  const cardUrl = typeof window !== "undefined" ? `${window.location.origin}/creators/${ctx.snap.profile.slug}` : "";
  return (
    <section className="page visible" id="page-community" data-screen-label="Community">
      <div className="cr-com">
        <header className="cr-com-head"><div><h1>Community</h1><div className="page-sub">Learn with other B2B creators, share what works and make your Naano identity visible.</div></div><span className="cr-com-live"><i /><span>Creator network</span></span></header>
        <div className="cr-com-grid">
          <section className="cr-com-card cr-com-slack">
            <div className="cr-com-slack-main">
              <div className="cr-com-slack-visual"><img src="/lp/slack-logo.png" alt="Slack" /><div className="cr-com-slack-faces" aria-hidden="true">{CREATORS.slice(20, 28).map((c) => <span key={c.slug} className="cr-com-slack-face" style={{ display: "inline-flex", alignItems: "center", justifyContent: "center", background: "#E6EDFF", color: "#1D5BF5", fontWeight: 700, fontSize: 11 }}>{initials(c.name)}</span>)}</div></div>
              <div className="cr-com-slack-copy"><span className="cr-com-eyebrow">Naano creators on Slack</span><h2>The room where B2B creators get better together.</h2><p>Ask for feedback on a sponsored post, compare campaign lessons, meet creators in your language and help shape what Naano builds next.</p></div>
            </div>
            <div className="cr-com-benefits"><span><iconify-icon icon="ph:check-circle-fill" /><span>Get feedback before you publish</span></span><span><iconify-icon icon="ph:check-circle-fill" /><span>Share campaign tips that work</span></span><span><iconify-icon icon="ph:check-circle-fill" /><span>Talk directly with the Naano team</span></span></div>
            <a className="btn btn-primary cr-com-slack-cta" href="#" onClick={(e) => { e.preventDefault(); ctx.toast("Slack invitations are sent once your card is live"); }}><img src="/lp/slack-logo.png" alt="" /><span>Join the Slack community</span><iconify-icon icon="ph:arrow-square-out" /></a>
          </section>
          <section className="cr-com-card cr-com-linkedin">
            <div className="cr-com-li-head"><div className="cr-com-li-icon"><img src="/linkedin-official.png" alt="LinkedIn" /></div><div><span className="cr-com-eyebrow">LinkedIn visibility</span><h2>Turn your LinkedIn profile into an always-on Deal Link</h2></div></div>
            <p className="cr-com-li-intro">Add your creator card to LinkedIn so brands can discover your work and join Naano through your attributed link.</p>
            <div className="cr-com-affiliate-benefit"><span><b>25%</b><small>of Naano's commission for 3 months</small></span><p>Leave your card on your LinkedIn profile. If a brand joins Naano through it, your reward is tracked automatically.</p></div>
            <div className="cr-com-li-experience"><span className="cr-com-li-company-logo"><img src="/lp/naano-logomark.png" alt="Naano" /></span><span className="cr-com-li-company-copy"><b>Naano Creator</b><span>Naano · Independent</span><small>Present</small></span></div>
            <div className="cr-com-mini-stage"><CreatorCardPreview d={ctx.cardData()} compact flippable={false} /></div>
            <button className="btn btn-primary cr-com-linkedin-cta" onClick={() => { navigator.clipboard?.writeText(cardUrl); ctx.toast("Card link copied — add it to your LinkedIn experience"); }}><iconify-icon icon="ph:share-network" /><span>Publish my card</span><iconify-icon icon="ph:arrow-right" /></button>
          </section>
        </div>
        <section className="cr-com-card cr-com-board">
          <div className="cr-com-board-head"><div><h2>Naano campaign leaderboard</h2><p>Estimated impressions generated by sponsored posts published for Naano brand collaborations.</p></div><div className="cr-com-seg" role="group" aria-label="Leaderboard metric"><button className={metric === "impressions" ? "on" : ""} onClick={() => setMetric("impressions")}>Estimated impressions</button><button className={metric === "posts" ? "on" : ""} onClick={() => setMetric("posts")}>Posts</button></div></div>
          <div className="cr-com-list" aria-live="polite">
            {board.map((b, i) => { const v = metric === "impressions" ? b.impressions : b.posts; return (
              <a className="cr-com-row" key={b.slug} href={`/creators/${b.slug}`} target="_blank" rel="noopener noreferrer">
                <span className={`cr-com-rank${i < 3 ? ` top r${i + 1}` : ""}`}>{i + 1}</span>
                <span className="cr-com-avatar" style={{ display: "inline-flex", alignItems: "center", justifyContent: "center", background: "#E6EDFF", color: "#1D5BF5", fontWeight: 700 }}>{initials(b.name)}</span>
                <span className="cr-com-person"><b>{b.name}</b><span>Public creator card</span></span>
                <span className="cr-com-progress"><i style={{ width: `${(v / max) * 100}%` }} /></span>
                <span className="cr-com-value"><b>{metric === "impressions" ? fmtK(v) : v}</b><small>{metric === "impressions" ? "estimated Naano impressions" : "posts"}</small></span>
              </a>
            ); })}
          </div>
        </section>
      </div>
    </section>
  );
}
