export const registry: Record<string, { load: () => Promise<{ default: React.ComponentType }>; title: string; description: string }> = {
  "devtools": { load: () => import("@/generated/pages/for__devtools"), title: "B2B Influencer Marketing for Devtools | Naano", description: "Sponsor developer creators on LinkedIn: engineering audiences, fixed per-post pricing from €20, median CPL €19 and the highest click-to-demo conversion of any vertical (Q1 2026, n=47)." },
  "fintech": { load: () => import("@/generated/pages/for__fintech"), title: "B2B Influencer Marketing for Fintech | Naano", description: "Sponsor finance and fintech creators on LinkedIn: CFO-audience voices, compliance-aware briefs, fixed per-post pricing from €20, median CPL €19 (Q1 2026, n=29 campaigns)." },
  "hr-tech": { load: () => import("@/generated/pages/for__hr-tech"), title: "B2B Influencer Marketing for HR-Tech | Naano", description: "Run LinkedIn creator campaigns for HR-tech: People Ops and talent-leadership creators, fixed per-post pricing from €20, median CPL €20 (Q1 2026, n=34 campaigns)." },
  "marketing-ops": { load: () => import("@/generated/pages/for__marketing-ops"), title: "B2B Influencer Marketing for Martech & Marketing-Ops | Naano", description: "The cheapest vertical on Naano: martech and demand-gen creators, fixed per-post pricing from €20, median CPL €16 (Q1 2026, n=36 campaigns)." },
  "product": { load: () => import("@/generated/pages/for__product"), title: "B2B Influencer Marketing for Product & PM Tools | Naano", description: "Reach product managers through LinkedIn creators: PM and product-leadership voices, fixed per-post pricing from €20, median CPL €18 (Q1 2026, n=39 campaigns)." },
  "revops": { load: () => import("@/generated/pages/for__revops"), title: "B2B Influencer Marketing for RevOps SaaS | Naano", description: "Reach RevOps leaders through the LinkedIn creators they already read: fixed per-post pricing from €20, median CPL €17 (Q1 2026, n=41 campaigns)." },
  "sales-tech": { load: () => import("@/generated/pages/for__sales-tech"), title: "B2B Influencer Marketing for Sales-Tech SaaS | Naano", description: "Run LinkedIn creator campaigns for sales-tech products: vetted SDR, AE and sales-leadership creators, fixed per-post pricing from €20, median CPL €16 (Q1 2026, n=58 campaigns)." },
  "vertical-saas": { load: () => import("@/generated/pages/for__vertical-saas"), title: "B2B Influencer Marketing for Vertical SaaS | Naano", description: "Creator campaigns for niche-industry SaaS (legal-tech, construction-tech, insurance-tech): rare niche voices, fixed per-post pricing from €20, median CPL €21 (Q1 2026, n=28)." },
};
